import AppLayout from '@/components/app-layout';
import { mockClassroomData } from '@/lib/mock-classroom-data';
import { BellCurveChart } from './bell-curve-chart';
import { StudentList } from './student-list';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Lightbulb, Shield } from 'lucide-react';

export default function ClassroomOverviewPage({ searchParams }: { searchParams?: { view?: string } }) {
  const isAdminView = searchParams?.view === 'admin';

  return (
    <AppLayout>
      <div className="flex-1 space-y-4 p-4 sm:p-8 pt-6">
        <div>
            <h1 className="text-3xl font-bold tracking-tight font-headline">
              Classroom Overview
            </h1>
            <p className="text-muted-foreground">
              Analyze your classroom's writing performance at a glance.
            </p>
        </div>
        <div className="space-y-6">
            {isAdminView && (
                <Alert variant="default" className="border-primary/50 bg-primary/5">
                    <Shield className="h-4 w-4 text-primary" />
                    <AlertTitle className="font-semibold">Administrator View</AlertTitle>
                    <AlertDescription>
                        You are viewing this classroom as an administrator.
                    </AlertDescription>
                </Alert>
            )}

            <BellCurveChart students={mockClassroomData} />
            
            <Card>
                <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                        <Lightbulb className="w-5 h-5 text-primary" />
                        Understanding the Scores
                    </CardTitle>
                    <CardDescription>How the AI calculates the overall student score.</CardDescription>
                </CardHeader>
                <CardContent className="text-sm text-muted-foreground">
                    <p>
                        The "Overall Score" is a composite metric generated by our AI analysis engine. It provides a holistic view of a student's writing proficiency based on their most recent work. This score is a weighted average of several key factors analyzed by the AI, including:
                    </p>
                    <ul className="list-disc pl-5 mt-2 space-y-1">
                        <li><strong>Grammar & Mechanics:</strong> The accuracy of spelling, punctuation, and sentence structure.</li>
                        <li><strong>Clarity & Cohesion:</strong> The logical flow of ideas and ease of understanding.</li>
                        <li><strong>Vocabulary Richness:</strong> The diversity and appropriateness of word choice.</li>
                        <li><strong>Sentence Complexity:</strong> The variety and structure of sentences used.</li>
                    </ul>
                    <p className="mt-2">
                        This score is intended to be a snapshot to help you quickly identify students who may be excelling or struggling. For a more detailed breakdown, please refer to the individual Student Performance Analysis reports.
                    </p>
                </CardContent>
            </Card>

            <StudentList students={mockClassroomData} />
        </div>
      </div>
    </AppLayout>
  );
}
